### ISSUE TITLE
strange "peaks" in S11 after upgrading to 0.2.1 and higher

### ISSUE THREAD

**Issue by df6dbf** [ttrftech/NanoVNA#59]
Have here "strange" Peaks after upgrading to v0.2.1. v0.2.2 shows same behaviour. Took Screenshots with nanoVNA-saver to show the Problem. The v0.2.0 from 27. Sept. seems ok.

Screenshot from 0.2.0 (27.Sept)
![pre0 2 1-270919](https://user-images.githubusercontent.com/19621920/65831183-0e667900-e2b7-11e9-948f-eb87fee45030.JPG)

Screenshot from 0.2.2 (29.Sept)
![after0 2 1-290919](https://user-images.githubusercontent.com/19621920/65831184-11616980-e2b7-11e9-8925-1697354fa499.JPG)

**Comment by EB4FBZ** [comment]
I can't reproduce this issue. Just updated from 0.1.1 to 0.2.2 and the response of a filter is the same in both versions.

**Comment by qrp73** [comment]
cannot reproduce

**Comment by gaionim** [comment]
> Have here "strange" Peaks after upgrading to v0.2.1. v0.2.2 shows same behaviour. Took Screenshots with nanoVNA-saver to show the Problem. The v0.2.0 from 27. Sept. seems ok.

are You using multiple segments in nanovna-saver ?
I have similar Peaks, but only in nanovna-saver with multiple segments.

**Comment by df6dbf** [comment]
Yes, its occured only in Multi-Segment Mode.

**Comment by edy555** [comment]
This issue is caused by behavior change of `sweep` command at 0.2.0.

This commit https://github.com/ttrftech/NanoVNA/commit/3fc17e18f900c6bb31fb1e72bab345adf576c15c shall make equivalent to former behavior. When I tested NanoVNA-saver 0.1.0 in multisegment mode with new firmware, it works well.

New [release 0.2.3](https://github.com/ttrftech/NanoVNA/releases/tag/0.2.3) is available including commit above.
Could you check it out?

**Comment by df6dbf** [comment]
Installed the 0.2.3 and tested with actual Version of nanoVNA-saver. It seems the problem is solved. Thank you! :)
